spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
server:
  port: 8080
  context-path: /choosepaper
druid:
  datasource:
    url: jdbc:mysql://localhost:3306/choosepaper?characterEncoding=utf8&tinyInt1isBit=false&serverTimezone=GMT%2B8
    username: test
    password: test
mybatis:
  config: classpath:mybatis-config.xml
